# Generated by Django 3.0.6 on 2020-12-24 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicleType', '0001_initial'),
        ('category', '0001_initial'),
        ('contactPerson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('license_number', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=200)),
                ('model_year', models.IntegerField()),
                ('price_per_km', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('CO2Emission', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
                ('air_condition', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=50)),
                ('bags', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('truck_height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('truck_capacity', models.IntegerField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photo/%y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photo/%y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photo/%y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photo/%y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photo/%y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photo/%y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactPerson.Contact_person')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleType.Vehicle_type')),
            ],
        ),
    ]
