# Generated by Django 3.0.6 on 2020-12-25 09:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='CO2Emission',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='air_condition',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bags',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seats',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='truck_capacity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='truck_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
