# Generated by Django 3.0.6 on 2021-01-01 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201225_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=400)),
                ('listing_id', models.IntegerField()),
                ('username', models.CharField(max_length=60)),
                ('user_id', models.IntegerField()),
                ('pickup_point', models.CharField(blank=True, max_length=400, null=True)),
                ('destination', models.CharField(blank=True, max_length=400, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=20, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='license_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
