# Generated by Django 3.0.6 on 2021-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210101_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbooking',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='pickup_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='return_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
