# Generated by Django 3.0.6 on 2021-01-03 13:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='footer_text_3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
