# Generated by Django 3.0.6 on 2020-12-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='photo/%y/%m/%m')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
