# Generated by Django 3.0.6 on 2020-12-25 09:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactPerson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
